### ISSUE TITLE
Sort out creating a Jekyll docker organization.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker#1]
Once we have a docker organization under @parkr's control and we can push to it I'll update the repo and start using that one but since people might want to play for now I've left it on my docker profile.

**Comment by parkr** [comment]
A docker organization?

**Comment by parkr** [comment]
Ah on docker.io. Yep, just set it up. Do I invite you?

**Comment by envygeeks** [comment]
Fixed up, if anybody else needs access talk to @parkr.
