### ISSUE TITLE
Image seems quiet useless

### ISSUE THREAD

**Issue by funkyfuture** [jekyll/docker#10]
maybe i'm missing something, if so blame the documentation, but here's some points from my experience with this image:

- it will start some funky stuff like a syslog-daemon for whatever reason
- no `jekyll`-executable will be invoked on startup

there is a `startup`-script running that is propably the entrypoint. about which you can only guess where it comes from, propably the `envygeeks/ruby`-image whose source is not available. it obviously doesn't care about any command, like the `jekyll s` in the example.

it would be convenient to configure the listening port via an environment variable or provide an image labelled `:web` that let's jekyll listen to port 80.

i see no use in patching, as the `grahamc/jekyll`-image is simply usable. but it's rather disappointing for an 'official' image.

also allowing customization in `/usr/bin/setup` is useless, such things should either be done in sub-images and/or on startup of a container.

**Comment by envygeeks** [comment]
Come back when you can be constructive.  The bugs have been noted but your other worthless comments will be ignored and this ticket closed.  Next time please use the (I assume it's still free) service called Google to find: https://github.com/envygeeks/dockerfiles/tree/master/images/ruby

**Comment by envygeeks** [comment]
And to add a note, /usr/bin/setup isn't there for you to customize, it's there for readability in the setup of the image itself, anybody who has ever worked with docker extensively (or even really at all) already knows that Dockerfiles don't lend itself to small images so you either use && everywhere or create a bash script to run all the stuff you need.

**Comment by funkyfuture** [comment]
> Come back when you can be constructive.

that was my intention when i pointed at my disappointed ux and mentioned an to me obvious documentation- and / or implemenatation-error.

> Next time please use the (I assume it's still free) service called Google to find

i expect these linked here: https://registry.hub.docker.com/u/envygeeks/ruby/

> /usr/bin/setup isn't there for you to customize

well, to me this comment in `setup` sounds like it's the supposed place for customization:

    # Any default plugins we want to include go here!

**Comment by envygeeks** [comment]
> that was my intention when i pointed at my disappointed ux and mentioned an to me obvious documentation- and / or implemenatation-error.

It was an implementation error carried over from the start of us building a server image for people who want to run Jekyll the way Github does, that has since been fixed (already and pushed to the public images.) in https://github.com/jekyll/docker/commit/2d2c586f7f16d2172f8d821aa36f0d7a5736f042 so the examples provided do work now, along with us also now defaulting to starting a `jekyll s` by default if you don't pass any arguments.

> i expect these linked here: https://registry.hub.docker.com/u/envygeeks/ruby/

Then nicely file a ticket on the linked repo and ask for that to happen and it might, but what you expect and what happens are two different things and if things aren't as expected approach things and ask for a fix without assuming everybody can preemptively read your mind, this isn't minority report.

> well, to me this comment in setup sounds like it's the supposed place for customization:

It says "we" as in @jekyll/core not "you" as in "you the user" but soon (as in here in probably less than an hour) we'll start accepting and installing gems you provide in a Gemfile in your Jekyll root, it's the least we can do to make it easy to get started quickly.

**Comment by funkyfuture** [comment]
> in 2d2c586 so the examples provided do work now

ah, so it was constructive. you could reflect this change in the documentation.

> assuming everybody can preemptively read your mind, this isn't minority report.

but now you guessed you could read my mind. ;-) i didn't assume that, i just expected what i perceived as a good convention so far.

> It says "we" as in @jekyll/core

there's no indication whether it's the inclusive or the exclusive we. in open-source i'm used to an inclusive we.

**Comment by envygeeks** [comment]
I've never met a project where inclusive we meant anything more than input, if we (or any project) were inclusive then the world would have full-write access which makes we inside of source exclusive in most cases but you are free to edit what you like and even send pull requests (which is always inclusive.)

I am willing to accept any input or bug whether it was written wrong or not, but the lack of constructive was the title and most of the input which assumes that the UX was meant to be bad and not a mistake when something else happened, that's a horrible way to approach things.

On the other things: I did say there were bugs that were noted and would be fixed but majority was nonconstructive therefore the entirety was labeled nonconstructive with only pieces cherry-picked.
