### ISSUE TITLE
htmlproof missing from :builder?

### ISSUE THREAD

**Issue by NioTeX** [jekyll/docker#100]
Was html-proofer removed from the builder tag?

I just changed our CI to use the latest :builder tag of the image, but now I get an error like so:
```bash
htmlproof "$PROJECT_DIR" --disable-external --empty-alt-ignore --allow-hash-href
bash: line 30: htmlproof: command not found
```

The image that was automatically built from a fork I created a few months ago worked well, and I couldn't find a commit since then that would have removed html-proffer.

What we were using till now: https://github.com/LynxSolutions/jekyll-docker

Any ideas?

**Comment by envygeeks** [comment]
`htmlproof` is no longer a command and since we've updated our images and we do not constrain base dependencies you were struck by the change like most people are.  You need use `htmlproofer` see: https://github.com/gjtorikian/html-proofer/commit/7af3adde736e84da2837460f2e783107bdcace06

Sorry!

**Comment by NioTeX** [comment]
Thanks for the response, but by the time I could test you updated the builder image again, and now the jekyll command is not working :)

Posted my issue here: 
https://github.com/jekyll/docker/issues/101
