### ISSUE TITLE
Container terminates due to runsvdir: not found

### ISSUE THREAD

**Issue by rdgoite** [jekyll/docker#104]
I pulled the latest version of `jekyll/jekyll` (both `:latest` and `:pages`), and every time I run a container based on it, it terminates with the following message in its logs:

```
﻿/usr/local/bin/startup: line 50: runsvdir: not found
/usr/local/bin/startup: line 51: runsvdir: not found
/usr/local/bin/startup: line 18: sv: not found
```

**Comment by envygeeks** [comment]
This is an upstream regression.  There is no need to file a ticket as Hulk has noted it. Templates are being re-issued and the bug has been fixed in https://github.com/envygeeks/docker-template
