### ISSUE TITLE
Alpine-based image won't work as a development environment on OSX

### ISSUE THREAD

**Issue by rthrfrd** [jekyll/docker#107]
Hello, I fully expect this to be closed as it's not a jekyll-specific issue, but just wanted to flag it for anyone else as there is no mention in any docs as far as I could see:

As far as I can tell (please correct me if there is a workaround), this image can't work on OSX as advertised* due possibly to a severe alpine/virtualbox interoperability bug where file changes on the host are not reflected in volumes within the container. Therefore even though jekyll correctly detects that the file has changed, the site is only rebuilt with the existing file contents.

I've documented some basic steps to reproduce the problem using the latest docker toolbox here:
https://github.com/docker/toolbox/issues/510#issuecomment-228027727

\* https://github.com/jekyll/docker/wiki/Usage:-Running#on-docker-machine--docker-toolbox

**Comment by rthrfrd** [comment]
Sure I'll give it a go a little later, thanks for the quick response!

**Comment by rthrfrd** [comment]
@envygeeks Had a go but going back from `apk` to `apt-get` etc. is a bit over-complicated for my needs and don't have the time, so just extending from docker official ruby and installing jekyll from there. Will hopefully be able to try this with native docker in future!

**Comment by envygeeks** [comment]
At this time we are happy with Alpine as it's much faster at updating packages than other providers like Ubuntu and much much faster than Debian.  If other users find this ticket and would like to try the conversion back to Ubuntu we'll happily look at it, but for now this is being closed because I do not wish to put in the effort to move to Ubuntu.
