### ISSUE TITLE
Gemspec errror 

### ISSUE THREAD

**Issue by knguyen0105** [jekyll/docker#108]
I'm trying Jekyll on Windows with this image.  

```
$ git clone https://github.com/swanson/lagom.git
$ cd lagon-master
$ docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p $(docker-machine ip `docker-machine active`):4000:4000 \
    jekyll/jekyll
```
but I keep getting many GemspecErrors, like

```
$ docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll   -it -p $(docker-machine ip `docker-machine active`):4000
:4000     jekyll/jekyll
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using addressable 2.4.0
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using ffi 1.9.10

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/multipart-post-2.0.0.gem. It may be corrupted.
Using gemoji 2.1.0
Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/net-dns-0.8.0.gem. It may be corrupted.
Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/public_suffix-1.5.3.gem. It may be corrupted.
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/rouge-1.10.1.gem. It may be corrupted.
Using safe_yaml 1.0.4
Using jekyll-feed 0.5.1
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using jekyll-paginate 1.1.0
Using jekyll-sitemap 0.10.0

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/terminal-table-1.6.0.gem. It may be corrupted.
Using bundler 1.12.5
Using tzinfo 1.2.2
Using coffee-script 2.4.1
Using ethon 0.9.0
Using rb-inotify 0.9.7
An error occurred while installing multipart-post (2.0.0), and Bundler cannot
continue.
Make sure that `gem install multipart-post -v '2.0.0'` succeeds before bundling.
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

```

is the problem with the image or with rubygems.org? Thanks.

**Comment by typhoon2099** [comment]
I'm having the same issue:
`Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Using execjs 2.7.0
Using colorator 0.1

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/csspool-st-3.1.2.gem. It may be corrupted.
Using json 1.8.3
Using ffi 1.9.10

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/htmlentities-4.3.4.gem. It may be corrupted.
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.12.5

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/autoprefixer-rails-6.3.6.2.gem. It may be corrupted.
An error occurred while installing csspool-st (3.1.2), and Bundler cannot
continue.
Make sure that `gem install csspool-st -v '3.1.2'` succeeds before bundling.`

**Comment by TheSpyder** [comment]
It seems to be related to having a Gemfile. My errors:

```
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using colorator 0.1

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/eventmachine-1.2.0.1.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/http_parser.rb-0.6.0.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/ffi-1.9.13.gem. It may be corrupted.

Bundler::GemspecError: Could not read gem at /usr/lib/ruby/gems/2.3.0/cache/git-1.3.0.gem. It may be corrupted.
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.12.5
An error occurred while installing eventmachine (1.2.0.1), and Bundler cannot
continue.
Make sure that `gem install eventmachine -v '1.2.0.1'` succeeds before bundling.
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

My Gemfile:
```
source "https://rubygems.org"

gem "jekyll"
gem "git"
group :jekyll_plugins do
  gem 'hawkins'
end
```

If I remove the Gemfile (and the things that need those extra gems) it runs without any problems. I also tried opening an interactive shell (without Gemfile) and these problematic gems won't install unless I `apk install -U build-base ruby-dev libffi-dev`.

Should we be building a custom docker image with these extra gems? The wiki documentation isn't very clear about that.

**Comment by envygeeks** [comment]
We don't want them included... sorry.  That sounds brash without explanation.   What you have is an actual error with `apk` and Alpine, not an error with Gem.  Dependencies are installed *after* an happens and then we try again, there is a bug in that system, probably related to our removal of sudo.

**Comment by typhoon2099** [comment]
It was working previously so I agree that a recent change must have caused the error. I've reverted to installing Jekyll on my machine for the time being, I was hoping to get to grips with docker so that I could move towards a more automated build/deployment process. I guess it will have to wait for now...

**Comment by TheSpyder** [comment]
That's fair enough. Looking closer that does appear to be a sudo error at the end. I might try to build a custom image in the meantime :)

**Comment by baptistedonaux** [comment]
Same fail to install Gems.

**Comment by envygeeks** [comment]
This issue is being closed out since it's been fixed upstream and a new release is coming this afternoon.
