### ISSUE TITLE
why not include docs?

### ISSUE THREAD

**Issue by asashnov** [jekyll/docker#109]
Why not include jekyll-docs to the official docker image?
It will allow me to browse Jekyll manual in offline.

 $ docker pull jekyll/jekyll:pages

 $ docker run -it -p 127.0.0.1:4000:4000 jekyll/jekyll:pages \
   jekyll docs
 You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.

**Comment by envygeeks** [comment]
I can't tell if this is a request for us to include it by default?
