### ISSUE TITLE
Mounting issue on windows due to Alpine linux base

### ISSUE THREAD

**Issue by DieterDePaepe** [jekyll/docker#115]
I'm running docker on a Windows 7 x64 machine.
Docker: Docker version 1.11.2, build b9f10c9
VirtualBox: 5.1.2

I have 2 files in folder:
```
# Running this in the Docker Quickstart Terminal
TW06C212+dieter@tw06c212 MINGW64 ~/Documents/folder (gh-pages)
$ cat Hello1.html
Hello world!
TW06C212+dieter@tw06c212 MINGW64 ~/Documents/folder (gh-pages)
$ cat Hello2.html
---
---
Hello Moon!
```

I start Jekyll:
`docker run --rm --label=jekyll -it -p 4000:4000 --volume=$(pwd):/srv/jekyll jekyll/jekyll jekyll build -w --force_polling`
Both files are generated in the `_sites` folder with correct content, as expected.

Now I change the files (in my windows host) to:
```
Bye world!
```
and
```
---
---
Bye Moon!
```
The changes are picked up by the watching jekyll:
```
      Regenerating: 1 file(s) changed at 2016-07-29 08:29:42 ...done in 0.009056
228 seconds.
      Regenerating: 1 file(s) changed at 2016-07-29 08:29:46 ...done in 0.014957
728 seconds.
```
However, something went wrong in the output files:
```
C:\Users\didpaepe\Documents\folder\_site>type Hello1.html
Hello worl
C:\Users\didpaepe\Documents\folder\_site>type Hello2.html
Bye Moon!
```

The first file didn't regenerate correctly. Stopping the jekyll watcher and restarting it (but leaving the docker VM running) does not fix the problem. Note that I've had similar problems with files with front matter, but I didn't find a clear pattern there.

I investigated this a bit, and it seems that the container does not see the proper file content. This seems to be linked to the Alpine distribution being used. See: https://github.com/gliderlabs/docker-alpine/issues/203

**Comment by envygeeks** [comment]
We don't use Docker's Alpine or Glider Glabs Alpine, we use EnvyGeeks Alpine which is a bit ahead of theirs a bit different.  That said, this isn't actually an Alpine error, this is a VirtualBox problem and is known upstream at Docker Toolbox and Docker Machine, it's this problem mixed with other more severe networking problems that prompted native Docker on Windows and OS X.

Sadly there is nothing we can do about this except keep pushing people towards native Docker or Docker Via Ubuntu in Windows Anniversary.  I've experienced this as well on both Ubuntu and Debian images we maintain and there is a bigger ticket about this issue already in our tracker.

**Comment by DieterDePaepe** [comment]
Quite unfortunate, since not everyone has Windows 10 (needed for native docker). I hoped this could have been caused by Alpine. Oh well, feel free to close this issue I guess. :)

**Comment by envygeeks** [comment]
Closing this as an upstream bug.
