### ISSUE TITLE
jekyll 3.2.0 | Error:  Permission denied @ dir_s_mkdir - /Users/_site

### ISSUE THREAD

**Issue by rajeshtg78git** [jekyll/docker#116]
I am using this DockerFile with Jekyll to run.

FROM jekyll/jekyll
WORKDIR /Users
COPY . /Users
ENTRYPOINT ["jekyll", "serve", "--host=0.0.0.0"]

The docker build is success. docker build -t myblog.com .

When I ran the run command : docker run -d -p 4000:4000 --name=myblog myblog.com

 I am getting the error : 

Configuration file: /Users/_config.yml
            Source: /Users
       Destination: /Users/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.2.0 | Error:  Permission denied @ dir_s_mkdir - /Users/_site

Pls help on this.

**Comment by phylor** [comment]
The Jekyll docker image is using a `USER jekyll` directive to change all commands to be run as user `jekyll`. This is supposed to increase security, but unfortunately leads to many permission problems, especially when using volumes.

In your case, docker's `COPY` sets the user and group to `root`. As your entrypoint (`jekyll serve`) is not run as `root`, it is not able to build into `_site`.

You can solve that by adding the following line in your Dockerfile, just after the `COPY` directive:

    RUN chown -R jekyll /Users

**Comment by rajeshtg78git** [comment]
Thank you for the information. But some how I used the WORKDIR as /src/Jekyll then it works without any issue.

**Comment by phylor** [comment]
Makes sense, because there already is a `chown jekyll:jekyll` on `/srv/jekyll` in jekyll's Dockerfile.

**Comment by envygeeks** [comment]
Yup, if you upload to a custom directory you should probably chown that directory so that the Jekyll user has access to it.  If you ship it into /srsv/jekyll, then as @phylor we will chown it for you and make sure it's available to try and ease the pain you felt.

@phylor's advice is proper if you really wish a custom WORKDIR.
