### ISSUE TITLE
location of .apk file in root - where is root?!

### ISSUE THREAD

**Issue by helt** [jekyll/docker#117]
https://github.com/jekyll/docker/wiki/APK:-System-Packages mentions, that additional packages can be installed by placing a file called `.apk` into the root directory. Is this the directory, where `_config.yml` and `Gemfile` are located?

**Comment by envygeeks** [comment]
We only have on root, and that's Jekyll's root.  And yes that is where _config.yml is.  Questions should be asked at https://talk.jekyllrb.com, this ticket system should be reserved for bugs only.
