### ISSUE TITLE
Unable to build using `github-pages` Gem

### ISSUE THREAD

**Issue by azizur** [jekyll/docker#121]
I have a project `Gemfile` with following:

```
source "https://rubygems.org"

gem 'github-pages'

```

When I run:
```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll   -it -p 127.0.0.1:4000:4000 jekyll/jekyll
```

I am getting:

```
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated json 2.0.2, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
       	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
       	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
       	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
       	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
       	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<main>'
sh: can't kill pid 701: No such process
```
Is this a known issue?

**Comment by envygeeks** [comment]
We provide `jekyll/pages` for Github Pages users, it provides everything you need.   The error you are getting is not a problem with the image (at least from what I am reading, I'll need more context if you think it is.) It's a conflict with your Gemfile.lock and another Gem that wants another version of JSON.

My suggestion would be to use the `jekyll/pages` gem as adding `github-pages` yourself is unsupported, we only support the loading of plugins (of which the pages gem doesn't support anyways.)

**Comment by azizur** [comment]
Oddly enough it was not using my Gem as instructed by my gem file. So when I run
`docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll   -it -p 127.0.0.1:4000:4000 jekyll/jekyll bundle exe jekyll serve` It just worked.

**Comment by envygeeks** [comment]
@azizur yes, we intentionally block all plugins on the jekyll/pages gem and refuse to even bundle install, we do this because it's what Github does, and we want you to have that expectation so that when you push to Github you aren't taken by surprise when plugins do not work.

**Comment by azizur** [comment]
@envygeeks According to [official Jekyll  docs GitHub Pages](http://jekyllrb.com/docs/github-pages/) my `Gemfile` is correct as to what Github pages gem will expect in github.io. This docker image should respect those. What I posted above is exactly what I have into my `Gemfile` nothing more, nothing less. I am not loading any additional gems/plugins.

Like you said, I do not want any surprises when I push to gihub. 

My assumption is that perhaps this docker images is not synced with what `github-pages` gem does.
