### ISSUE TITLE
creation of custom image w/ jekyll-assets (and imagemagick apk)

### ISSUE THREAD

**Issue by espinielli** [jekyll/docker#122]
I like the `jekyll/jekyll` docker image idea of building a small image, so
on top of it I am trying to build a development image to be used by all my teammates.

In a new directory, I created 3 files:
1. a simple `Dockerfile`:
   
   ``` docker
   FROM jekyll/jekyll:stable
   
   MAINTAINER E S <e.s@xyzzy.com>
   ENV REFRESHED_AT 2016-09-14
   ```
2. a `Gemfile`:
   
   ``` gemfile
   source 'https://rubygems.org'
   
   gem 'jekyll-assets'
   ```
3. a `.apk` file (in order to install `imagemagick`):
   
   ```
   imagemagick
   ```

When I execute `docker build  --rm -t "espin/pru-jekyll:v1" .` I successfully create the `espin/pru-jekyll:v1` image.
Unfortunatelly when I run it via

``` shell
$ docker run -ti --rm -v "$PWD:/srv/jekyll" -p 4000:4000 espin/pru-jekyll:v1 sh
```

I see the `jekyll-assets` gem being installed (which I though would have been part of the image...) and cannot find any imagemagick cli too, i.e. convert.

Is this the right way to proceed? (And the right place where to ask?)
Thank you in advance!

**Comment by envygeeks** [comment]
In the past we used to remove those dependencies after install, with the latest release we no longer do that, we keep those dependencies until exit.  It should be released in a few minutes one my CI confirms it works.
