### ISSUE TITLE
index.md can't build automatically

### ISSUE THREAD

**Issue by lufo816** [jekyll/docker#125]
If I add a new post, the Jekyll will generate a new .html file in _site, but it can't update index.html automatically. Here is my index.md. Everything is ok of I use Jekyll without Docker.

	---
	title: Home
	layout: page
	---

	<ul class="listing">
	{% for post in site.posts %}
	  {% capture y %}{{post.date | date:"%Y"}}{% endcapture %}
	  {% if year != y %}
	    {% assign year = y %}
	    <li class="listing-seperator">{{ y }}</li>
	  {% endif %}
	  <li class="listing-item">
	    <time datetime="{{ post.date | date:"%Y-%m-%d" }}">{{ post.date | date:"%Y-%m-%d" }}</time>
	    <a href="{{ site.url }}{{ post.url }}" title="{{ post.title }}">{{ post.title }}</a>
	  </li>
	{% endfor %}
	</ul>

**Comment by envygeeks** [comment]
This is a problem with Docker and is a known issue, if you are not on Linux use Docker Native for your operating system, if you are on Windows inside of Ubuntu SubSystem, use Polling, if you wish to continue to use what I assume is Docker Machine, please also force polling which will resolve this issue.
