### ISSUE TITLE
Container fails to install github-pages dependencies: permission denied

### ISSUE THREAD

**Issue by zarbis** [jekyll/docker#126]
I'm trying to bootstrap container for working with Github Pages.
Steps to reproduce:
- strart container with empty mounted host directory
- docker exec jekyll jekyll new . to bootstrap  site with `minima` theme
- stop container
- edit Gemfile as suggested: comment `jekyll` gem and uncomment github-pages gem:
  `gem "github-pages", group: :jekyll_plugins`
- restart container, wait for it to install gems
- get error:

```
Installing nokogiri 1.6.8.1 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.8.1
```

After doing some troubleshooting i've found that script `03-gem-depends` runs that command as `jekyll` user, which seems not to having permissions indeed.

```
chpst -u jekyll:jekyll docker-helper \
install_users_gems
```

Not sure which part to blame but seems like current setup is not capable of setting up gems with native extensions.

**Comment by envygeeks** [comment]
This is a known issue, that said, `github-pages` is not a plugin, it's a replacement for Jekyll, so use the `jekyll/docker:pages` tag because what you're doing is unsupported anyways as we don't support plugins at all for Github Pages even if you decide to game the system by using our normal images.

**Comment by zarbis** [comment]
@envygeeks thanks for quick response! I've pulled jekyll/jekyll:pages image. I wonder now what is a correct way to bootstrap new site? It `docker exec jekyll jekyll new .` a correct way?

Since it creates same structure as jekyll/jekyll:latest image with same Gemfile I'm in doubt it will work.
The sole reason I've started messing with Gemfile is because I was getting different result on localhost and on github.

**Comment by envygeeks** [comment]
@zarbis they create the same structure, the difference is that Github Pages includes plugins and shims that Core doesn't, hence it being a replacement and not a plugin,

**Comment by zarbis** [comment]
@envygeeks I'm still a bit confused on how to create local environment that will render exactly as Pages does.

I've bootstrapped sample site with `jekyll new` command and removed `Gemfile` completely, assuming that `jekyll/jekyll:pages` has everything Github Pages has.

Unfortunately I get differently rendered posts on local and remote sides. For example docker version renders as expected this fragment:
```
mylist:
- one
- two
- three
```
while Github will only render this as list if i have empty lines before and after list elements:
```
mylist:

- one
- two
- three

```

I'm new to Jekyll but these differences lead me to conclusion that there are different rendering engines/markdown dialects/different standards compliance level... you name it, on both sides.

In my understanding `Gemfile` is a way to remove this differences by specifying what exact components I'm using to render locally so Github uses the same, or vice versa.

Sorry for deviating from initial topic.

**Comment by envygeeks** [comment]
Your conclusions on different rendering engines are a tiny bit incorrect, Jekyll and Github pages both use Kramdown.  They might have differing Kramdown defaults though, which in theory would make this a bug in Github-Pages bug because we can do nothing about that here they would need to export their configurations into our Kramdown.  We've no idea what their configurations are.

> In my understanding Gemfile is a way to remove this differences by specifying what exact components I'm using to render locally so Github uses the same, or vice versa.

That only applies outside of Docker, this is Docker, we provide everything you need.  Github Pages no longer supports anything but Kramdown, and we do not support custom plugins within our Github-Pages image (though people can still run them up until I get unlazy and set Jekyll's safe mode -- but that doesn't really matter, that's a user bug.)

**Comment by mrleeio** [comment]
@envygeeks @zarbis Can you two elaborate on how to setup a new Jekyll site using the docker image?  What exactly are the required steps?  Is there a work around for installing the nokogiri gem?

**Comment by zarbis** [comment]
@mrleeio Unsatisfactory answer for you, I couldn't make it work as intended. I kept getting rendering differences between localhost and github. I gave up and ended up generating my site locally with whatever customizations i want and hosting Nginx container with my site on AWS Free Tier.

**Comment by bux578** [comment]
I got the docker image building with the following Dockerfile

Gemfile: https://github.com/acemod/ACE3/blob/master/docs/Gemfile

```
# Build:
# docker build -t ace3mod/jekyll .
#
# Run:
# docker run -it ace3mod/jekyll

FROM jekyll/jekyll:3.2.1
MAINTAINER bux

RUN apk --update add \
gcc \
build-base \
ruby-dev \
libc-dev \
linux-headers \
libffi-dev \
libxml2-dev \
libxslt-dev \
postgresql-dev

# jekyll server uses port 4000
EXPOSE 4000

COPY . /srv/jekyll

RUN gem install bundler

COPY Gemfile* /tmp/
WORKDIR /tmp

RUN bundle config build.nokogiri --use-system-libraries
RUN bundle install

WORKDIR /srv/jekyll
ENTRYPOINT ["bundle", "exec", "jekyll", "serve", "--future", "--incremental", "--config", "_config_dev.yml"]
```

I'm currently fighting with permissions, though. So this might not be the perfect way to do it. But maybe it could help you.

**Comment by jenglamlow** [comment]
Hi,

I'm getting the same error
```
←[36mjekyll_1  |←[0m Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/r
uby/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.8.1
```

Is this issue fixed yet? If not,  is there any workaround?

**Comment by absolutejam** [comment]
Same issue cloning a github-pages repo and trying to run locally using `jekyll/jekyll:pages`

**Comment by envygeeks** [comment]
This should be resolved in the latest release coming out in a few minutes.
