### ISSUE TITLE
docker-template missing

### ISSUE THREAD

**Issue by DjThossi** [jekyll/docker#129]
I'm still kind of new to docker environment. In addition I'd live to learn more about jekyll. Not sure if I'm just stupid or your documentation is not good enough. 

I tried your provided command
`bundle exec docker-template build jekyll/jekyll:pages`

First it told me to install bundler. Ok I got this. But now it tells me  
`bundler: command not found: docker-template`

And I cannot find correct lib or software I need to install in order to make it work.
Could you please help me?

In addition I'd love to see more docs about first steps and how I'm suppose to work with this container. So where to put the files. and and and.

**Comment by envygeeks** [comment]
You need to `bundle install` before you can `bundle exec docker-template`.
