### ISSUE TITLE
Permission denied when trying Wiki "Usage: Running" example

### ISSUE THREAD

**Issue by mjbright** [jekyll/docker#130]
I'm new to Jekyll itself, but this seems to be a basic permissions (or SELinux?) problem.

I've tried the "Native Docker" instruction from the Wiki page https://github.com/jekyll/docker/wiki/Usage:-Running.

```
> docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll
runsvdir /etc/startup3.d: fatal: unable to open current directory: access denied
runsvdir /etc/startup2.d: fatal: unable to open current directory: access denied
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.2.1 | Error:  Permission denied @ dir_initialize - .
sh: can't kill pid 39: No such process
```

I'm running docker 1.10.3 on Fedora 24 with SELinux enabled/enforcing.

My user id is 1000 (I read somewhere in an issue that you use uid 1000 in the image).

Here are the permissions on the directory from where I run the above docker run.

```
mjb@zBook ~/jekyll> ls -ld
drwxr-xr-x. 3 mjb mjb 4096 Nov  5 18:58 .
mjb@zBook ~/jekyll> ls -ldZ
drwxr-xr-x. 3 mjb mjb system_u:object_r:user_home_t:s0 4096 Nov  5 18:58 .
mjb@zBook ~/jekyll> id
uid=1000(mjb) gid=1000(mjb) groups=1000(mjb),10(wheel),975(vboxusers),978(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

Any thoughts?

**Comment by envygeeks** [comment]
Your system logs should provide more info.  Can you look through those and se if you can provide more information? This could be several things (SELinux like you already mentioned) but it could be UserNS or Seccomp (if you use it.)

**Comment by mjbright** [comment]
OK, fixed - it was an SELinux thing.

In a "Project Atomic" [blog post here](http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/), they mention setting of the context as follows

`chcon -Rt svirt_sandbox_file_t .`

After applying this I no longer get this error.
