### ISSUE TITLE
how to change timezone

### ISSUE THREAD

**Issue by alex-tu-cc** [jekyll/docker#131]
Hi,
I'm using the docker image on docker hub "jekyll/jekyll:pages 5a0d13d67749".
It's default timezone is GMT, so that all post which set to the current time of my timezone GMT+8 will not be generated.

ex. 
in docker shell:
bash-4.3# date
Sun Nov  6 03:26:32 GMT 2016

so if I write the current time of GMT+8 in header of post
    date:   2016-11-06 03:26:32

Then this post will not be generated.
I also tried changing /etc/timezone and commit then re-run the changed docker image,
but it's not work.
bash-4.3# cat /etc/timezone 
Asia/Taipei
bash-4.3# date
Sun Nov  6 03:33:55 GMT 2016

**Comment by fbau3r** [comment]
I found environment variable `TZ` useful: `-e "TZ=Asia/Taipei"`

Source: [request date and time settings or automatic time zone](https://github.com/sameersbn/docker-gitlab/issues/77#issuecomment-46346176)

Works on a Docker image based on `microsoft/aspnetcore:1.0.3` in my case.

**Comment by envygeeks** [comment]
Yes this should work, you can also ship `/etc/timezone`
