### ISSUE TITLE
Permission denied when running GitHub pages site in Jekyll/jekyll:pages

### ISSUE THREAD

**Issue by takacsmark** [jekyll/docker#133]
Hi,

I've bumped into permission issues when running a jekyll/jekyll:pages container on an existing GitHub page. I've created some workarounds with custom images, but every workaround is too complex, and none of them is perfect. Please help me find a simple and elegant way to solve this.

When I start my container the first time, it starts installing gems listed in my project's Gemfile.lock. This will result in several permission denied messages. 

Here is the Gemfile.lock:
GEM
  remote: https://rubygems.org/
  specs:
    RedCloth (4.2.9)
    activesupport (5.0.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    blankslate (2.1.2.4)
    classifier-reborn (2.0.4)
      fast-stemmer (~> 1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    colorator (0.1)
    concurrent-ruby (1.0.2)
    ethon (0.9.1)
      ffi (>= 1.3.0)
    execjs (2.7.0)
    faraday (0.10.0)
      multipart-post (>= 1.2, < 3)
    fast-stemmer (1.0.2)
    ffi (1.9.14)
    gemoji (2.1.0)
    github-pages (39)
      RedCloth (= 4.2.9)
      github-pages-health-check (~> 0.2)
      jekyll (= 2.4.0)
      jekyll-coffeescript (= 1.0.1)
      jekyll-feed (= 0.3.1)
      jekyll-mentions (= 0.2.1)
      jekyll-redirect-from (= 0.8.0)
      jekyll-sass-converter (= 1.3.0)
      jekyll-sitemap (= 0.8.1)
      jemoji (= 0.5.0)
      kramdown (= 1.5.0)
      liquid (= 2.6.2)
      maruku (= 0.7.0)
      mercenary (~> 0.3)
      pygments.rb (= 0.6.3)
      rdiscount (= 2.1.7)
      redcarpet (= 3.3.2)
      terminal-table (~> 1.4)
    github-pages-health-check (0.3.2)
      net-dns (~> 0.6)
      public_suffix (~> 1.4)
      typhoeus (~> 0.7)
    html-pipeline (1.9.0)
      activesupport (>= 2)
      nokogiri (~> 1.4)
    i18n (0.7.0)
    jekyll (2.4.0)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-feed (0.3.1)
    jekyll-gist (1.4.0)
      octokit (~> 4.2)
    jekyll-mentions (0.2.1)
      html-pipeline (~> 1.9.0)
      jekyll (~> 2.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.8.0)
      jekyll (>= 2.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-sitemap (0.8.1)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    jemoji (0.5.0)
      gemoji (~> 2.0)
      html-pipeline (~> 1.9)
      jekyll (>= 2.0)
    kramdown (1.5.0)
    liquid (2.6.2)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    maruku (0.7.0)
    mercenary (0.3.6)
    mini_portile2 (2.1.0)
    minitest (5.9.1)
    multipart-post (2.0.0)
    net-dns (0.8.0)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    octokit (4.6.1)
      sawyer (~> 0.8.0, >= 0.5.3)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.12)
    public_suffix (1.5.3)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rdiscount (2.1.7)
    redcarpet (3.3.2)
    safe_yaml (1.0.4)
    sass (3.4.22)
    sawyer (0.8.1)
      addressable (>= 2.3.5, < 2.6)
      faraday (~> 0.8, < 1.0)
    terminal-table (1.7.3)
      unicode-display_width (~> 1.1.1)
    thread_safe (0.3.5)
    toml (0.1.2)
      parslet (~> 1.5.0)
    typhoeus (0.8.0)
      ethon (>= 0.8.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    unicode-display_width (1.1.1)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  github-pages

BUNDLED WITH
   1.13.6

And the error messages:
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing RedCloth 4.2.9 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/RedCloth-4.2.9
Installing concurrent-ruby 1.0.2
Using i18n 0.7.0
Installing minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Installing blankslate 2.1.2.4
Installing fast-stemmer 1.0.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/fast-stemmer-1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Installing colorator 0.1
Using ffi 1.9.14
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Installing rb-fsevent 0.9.8
Installing kramdown 1.5.0
Installing liquid 2.6.2
Using mercenary 0.3.6
Installing posix-spawn 0.3.12 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/posix-spawn-0.3.12
Installing yajl-ruby 1.2.1 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/yajl-ruby-1.2.1
Installing redcarpet 3.3.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.3.2
Using safe_yaml 1.0.4
Installing jekyll-feed 0.3.1
Using mini_portile2 2.1.0
Installing jekyll-sitemap 0.8.1
Installing maruku 0.7.0
Installing rdiscount 2.1.7 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/rdiscount-2.1.7
Installing unicode-display_width 1.1.1
Using bundler 1.12.5
An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
fetch http://mirror.envygeeks.io/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/27) Upgrading musl (1.1.14-r11 -> 1.1.14-r14)
(2/27) Installing binutils-libs (2.26-r0)
(3/27) Installing binutils (2.26-r0)
(4/27) Installing isl (0.14.1-r0)
(5/27) Installing libgomp (5.3.0-r0)
(6/27) Installing libatomic (5.3.0-r0)
(7/27) Installing pkgconf (0.9.12-r0)
(8/27) Installing pkgconfig (0.25-r1)
(9/27) Installing mpfr3 (3.1.2-r0)
(10/27) Installing mpc1 (1.0.3-r0)
(11/27) Installing gcc (5.3.0-r0)
(12/27) Installing make (4.1-r1)
(13/27) Installing musl-dev (1.1.14-r14)
(14/27) Installing libc-dev (0.7-r0)
(15/27) Installing fortify-headers (0.8-r0)
(16/27) Installing g++ (5.3.0-r0)
(17/27) Installing build-base (0.4-r1)
(18/27) Upgrading musl-utils (1.1.14-r11 -> 1.1.14-r14)
(19/27) Installing libffi-dev (3.2.1-r2)
(20/27) Installing zlib-dev (1.2.8-r2)
(21/27) Installing libxml2-dev (2.9.4-r0)
(22/27) Installing libxslt-dev (1.1.29-r0)
(23/27) Installing readline-dev (6.3.008-r4)
(24/27) Installing libgmpxx (6.1.0-r0)
(25/27) Installing gmp-dev (6.1.0-r0)
(26/27) Installing ruby-dev (2.3.1-r0)
(27/27) Installing yaml-dev (0.1.6-r1)
Executing busybox-1.24.2-r11.trigger
OK: 250 MiB in 70 packages
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing RedCloth 4.2.9 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/RedCloth-4.2.9
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using blankslate 2.1.2.4
Installing fast-stemmer 1.0.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/fast-stemmer-1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using ffi 1.9.14
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.6
Installing posix-spawn 0.3.12 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/posix-spawn-0.3.12
Installing yajl-ruby 1.2.1 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/yajl-ruby-1.2.1
Installing redcarpet 3.3.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.3.2
Using safe_yaml 1.0.4
Using jekyll-feed 0.3.1
Using mini_portile2 2.1.0
Using jekyll-sitemap 0.8.1
Using maruku 0.7.0
Installing rdiscount 2.1.7 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/rdiscount-2.1.7
Using unicode-display_width 1.1.1
Using bundler 1.12.5
An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
fetch http://mirror.envygeeks.io/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
OK: 250 MiB in 70 packages
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing RedCloth 4.2.9 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/RedCloth-4.2.9
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using blankslate 2.1.2.4
Installing fast-stemmer 1.0.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/fast-stemmer-1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using ffi 1.9.14
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.6
Installing posix-spawn 0.3.12 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/posix-spawn-0.3.12
Installing yajl-ruby 1.2.1 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/yajl-ruby-1.2.1
Installing redcarpet 3.3.2 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.3.2
Using safe_yaml 1.0.4
Using jekyll-feed 0.3.1
Using mini_portile2 2.1.0
Using jekyll-sitemap 0.8.1
Using maruku 0.7.0
Installing rdiscount 2.1.7 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/rdiscount-2.1.7
Using unicode-display_width 1.1.1
Using bundler 1.12.5
An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<main>'
sh: can't kill pid 495: No such process

Thanks

**Comment by takacsmark** [comment]
I solved the issue in the least destructive way I could work out, and created a new image starting from the official Jekyll/jekyll:pages images. This way I can install all the dependencies fixed in Gemfile.lock. Here is my docker file for reference. 

FROM jekyll/jekyll:pages

COPY Gemfile* /srv/jekyll/

WORKDIR /srv/jekyll

RUN apk update && \
	apk add ruby-dev gcc make curl build-base libc-dev libffi-dev zlib-dev libxml2-dev libgcrypt-dev libxslt-dev python

RUN bundle config build.nokogiri --use-system-libraries && \
	bundle install

EXPOSE 4000

**Comment by envygeeks** [comment]
This is fixed with the latest release.
