### ISSUE TITLE
Docker run fails

### ISSUE THREAD

**Issue by lupa18** [jekyll/docker#134]
Runing with custom docker-compose or [command here](https://github.com/jekyll/docker/wiki/Usage:-Running#on-native-docker) same problem: 

```
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.223 seconds.
jekyll 3.2.1 | Error:  �q��
sh: can't kill pid 35: No such process

```

**Comment by envygeeks** [comment]
This issue should be filed upstream at https://github.com/jekyll/jekyll/issues/new, Jekyll is Core software.
