### ISSUE TITLE
Too much memory

### ISSUE THREAD

**Issue by mplacona** [jekyll/docker#137]
Hi, I have a Jekyll container running on a droplet, but it seems to be using a lot of memory. Wondering if this is normal, and if there's any way I can make it use less memory than that.

![memory](https://d1ro8r1rbfn3jf.cloudfront.net/ms_64922/99bsm4qMDiAKI08MfFlOzt2mEsGEEZ/1.%2Bplacona%2540placona-ubuntu%253A%2B%257E%252Fandroidsecurity.info%2B%2528ssh%2529%2B2016-12-29%2B12-21-32.png?Expires=1483100511&Signature=PbkECgHpwbZPpd-mUlwwSiF26zpcF7SZUbTFg0sLGR8jjAjeoxxKzZg7g46-eiaRlSw6V544GvCPX73iNHUGoCq-ZpNd7xxy2Fsuz3Xco0h0E2~SjLP9OxAZayddoVk-B0ZZ13a1s9n5NwFMORjAQ6cSrwBxkrIGvn5QoZBKlwkISS2WW3pQyze76LU-w6IimHquLQP-r0xgCgXFUZLqUqr--CO2Wa7W6gCpEOZ~wbX1UZeknmBnj4HEdcJE2nb~T-7aar95zIjoeFFS5Cj-k-wFspc5QTOrLCXL07a8VkyRlZ1FQAKn3keCRyK5BMeXzaxJRj4Oj-8o2J3y6bIs3g__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

This is just a simple Jekyll website with very little traffic and only about 6 blog posts.

Thank you

**Comment by gpen365** [comment]
Sorry, I have never used Jekyll container.

**Comment by envygeeks** [comment]
HI @mplacona this ticket belongs on Jekyll/Jekyll, we only ship Jekyll as a container and the modifications we make to Jekyll are only in the CLI.  I'm sure @jekyll/core would happily look into any memory leaks you might be having.
