### ISSUE TITLE
Add jekyll entrypoint to image

### ISSUE THREAD

**Issue by marcosnils** [jekyll/docker#140]
I remember previous versions of this docker image executed `jekyll serve` by default. I understand that this might not be the desired default command but the image but I believe adding `jekyll` as entrypoint would be helpfull as running the docker image will return jekyll help instead of "No command specified" error. 

WDTY?

**Comment by mpartipilo** [comment]
I was very confused about this step missing as well. Maybe it's to encourage people to create their own Dockerfiles or use it with Compose?

**Comment by envygeeks** [comment]
Entrypoints are a barrier and are (to me) non-essential.  I'm happy to add a default command but I don't think I will ever approve an entrypoint while I'm maintainer because it prevents rolling commands.  It's not a missing step, we expect you to run full commands.

**Comment by marcosnils** [comment]
:+1: thx!.
