### ISSUE TITLE
Add s3_website gem

### ISSUE THREAD

**Issue by jhabdas** [jekyll/docker#142]
Enables config-driven, repeatable zero-downtime deployments to S3 plus CloudFront (with 301 redirects) from the convenience of the command line.

https://github.com/laurilehmijoki/s3_website

Usage with Travis:
https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/#deploy-with-travis

I use it without Travis to deploy my Hugo site as well.

**Comment by jvtrigueros** [comment]
I don't mean to resurrect an old thread, but I had a question about how is one supposed to get `s3_website` working in the builder container since there's no Java installed. Is the intent that I use this as a base and install it myself?

**Comment by jhabdas** [comment]
Hmm. Good point 😂. Think that needs an Issue

**Comment by envygeeks** [comment]
I guess you can't, as I won't be putting Java on this image, even the OpenSource Java as Oracles legal speak makes me nervous, the best I could offer you is the official S3 Python package, which has S3 sync with the option to set headers and all that junk, it's a little less wrapped though.

**Comment by jvtrigueros** [comment]
It doesn't sound like the builder container is being used so maybe, just note that you gotta Bring Your Own Java.

**Comment by envygeeks** [comment]
The builder container is used by quite a few people, it was designed for CI's.  Most of them don't use jekyll/builder, they still use jekyll/jekyll:builder

**Comment by jvtrigueros** [comment]
I'm adding this here in case it helps someone else, the [jekyll](https://github.com/jekyll/docker/blob/master/repos/jekyll/copy/all/usr/local/bin/jekyll#L28) script installs any package in the `.apk` file. So as part of your CI step, you could create a file with:
```
openjdk8-jre@community
```
This will install OpenJDK 8 JRE which is sufficient to run `s3_website`.

For reference, an example file structure would look something like this:
```
.
├── .apk
├── .gitignore
├── .sass-cache
├── _config.yml
├── _posts
│   └── 2017-03-27-welcome-to-jekyll.markdown
├── _site
│   ├── about
│   ├── assets
│   ├── feed.xml
│   ├── index.html
│   └── jekyll
├── about.md
├── index.md
└── s3_website.yml
```

So there's no need to explicitly install Java during the `jekyll/jekyll:builder` image creation, as the user can specify which packages to install before running `jekyll` commands. This is awesome!
