### ISSUE TITLE
Latest image is broken when uid != 1000

### ISSUE THREAD

**Issue by tomdee** [jekyll/docker#145]
e.g. on semaphoreCI, the uid is 1003. This is a recent breakage/regression.

```
Semaphore (40 min left): ~/docs $ docker run  -ti --rm -v /home/runner/docs:/srv/jekyll jekyll/jekyll:3.3.1 jekyll build --incremental
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating... 
jekyll 3.4.0 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site

```

and
```
$ id 
uid=1003(runner) gid=1003(runner) groups=1003(runner),999(docker)
```

**Comment by tomdee** [comment]
I fixed this kind of issues on this repo over here - https://github.com/projectcalico/go-build/blob/master/Dockerfile

It requires the user to pass in their ID with an env var (or it will default to 9001)

**Comment by envygeeks** [comment]
We already do that: https://github.com/jekyll/docker/blob/master/repos/jekyll/copy/all/usr/local/bin/jekyll#L17

**Comment by tomdee** [comment]
Excellent, I tested that and it works!

`docker run -e JEKYLL_UID=`id -u`  -ti --rm -v /home/runner/docs:/srv/jekyll jekyll/jekyll:3.3.1 jekyll build --incremental
`
