### ISSUE TITLE
Jekyll environment isn't respected in 3.4

### ISSUE THREAD

**Issue by skoblenick** [jekyll/docker#147]
The `latest` i.e. `3.4.0` Docker container ignores the Jekyll environment variable when set.

Creating a `production` container with the following:

```
docker run -it -v "$PWD:/srv/jekyll" -e "JEKYLL_ENV=production" -p "4000:4000" jekyll/jekyll:3.4 bash
```

Validating environment variable:

```
echo $JEKYLL_ENV
production
```

Running:

`jekyll build` even `JEKYLL_ENV=production jekyll build`, with the layout templates`{{ jekyll.environment }}`, renders `development`

previous versions such as `3.2` or `3.2.1` correctly produce the expected results.

**Comment by envygeeks** [comment]
Thanks for the bug report!
