### ISSUE TITLE
Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by maklipsa** [jekyll/docker#150]
I get the above error when trying to run the docker image (on Windows):

`
docker run -it -p 5000:4000 -v //c/src/private/underdevtalk.github.io/:/srv/jekyll --name underdev jekyll/jekyll bundle exe jekyll serve
`

My gemfile looks like this:

`
source "https://rubygems.org"

gem 'github-pages'
`

**Comment by envygeeks** [comment]
Please provide more information, such as logs.

**Comment by maklipsa** [comment]
I've managed to solve it by changing the gem file from:

`source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
end
`

to:


`source "https://rubygems.org"

gem "json"
gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-gist"
`

**Comment by brando90** [comment]
I was doing:

```
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
```

but I get the error:

```
$ bundle update github-pages
Could not find gem 'github-pages'.
```

any help?

**Comment by jxb345** [comment]
@brando90 - I had the same error that you encountered, so I ran the following:

`bundle install`

then

`bundle update github-pages`

This worked for me although I cannot confirm that running `bundle install` is the best way (or even a good approach) to solving this particular issue.

**Comment by envygeeks** [comment]
@jxb345 it is, your local Gemfile is the authority even in an image that designates a version. That version is just the default, if you update, upgrade, or otherwise locally and then rerun the image, the Docker image will do as you asked!

**Comment by XiaosongWen** [comment]
Hi I am trying to setup the page through the https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll
However, when I tried to run 

> bundle exec jekyll serve

it keeps giving me this error:

> C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'github-pages (~> 206) x64-mingw32' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `each'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:49:in `start'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:22:in `resolve'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:258:in `resolve'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
        from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
My gemfile is:

> source "https://rubygems.org"
> gem "jekyll", "\~> 3.8.5"
> gem "minima", "\~> 2.5"
> gem "github-pages", "\~>  206", group: :jekyll_plugins
> group :jekyll_plugins do
>   gem "jekyll-feed", "\~> 0.12"
> end
I tried bundle update and bundle install, still give me this error

**Comment by seegler** [comment]
> @brando90 - I had the same error that you encountered, so I ran the following:
> 
> `bundle install`
> 
> then
> 
> `bundle update github-pages`
> 
> This worked for me although I cannot confirm that running `bundle install` is the best way (or even a good approach) to solving this particular issue.

Worked for me
