### ISSUE TITLE
GitHub Pages not rendered correctly

### ISSUE THREAD

**Issue by borekb** [jekyll/docker#155]
Steps to reproduce:

1. Create some new repo on GitHub, let it generate default `README.md` file.
2. Enable GitHub Pages for this repo. In my case, it now looks like this:

![image](https://cloud.githubusercontent.com/assets/101152/25749558/428792f2-31af-11e7-8da0-527f8462ab96.png)

![image](https://cloud.githubusercontent.com/assets/101152/25749580/50f68118-31af-11e7-975a-471bc9f2928f.png)

3. Clone the repo locally, start the Docker container as per wiki instructions:

```bash
$ docker run --rm -v %CD%:/srv/jekyll -it -p 4000:4000 jekyll/jekyll:pages jekyll serve
```

This is the result:

![image](https://cloud.githubusercontent.com/assets/101152/25750165/26c45a6c-31b1-11e7-8b0f-d8cc626905cb.png)

I'm not a previous GH Pages user but the current behavior seems to be in place at least since last December: [Publishing with GitHub Pages, now as easy as 1, 2, 3](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3). Maybe the ":pages" build is not updated for the recent GitHub Pages yet?

**Comment by envygeeks** [comment]
This ticket belongs to Jekyll, and it's not really a bug, this is the designed in behavior of Jekyll, Jekyll's serving requires an index.html, regardless of what Github does with their own servers, Jekyll and Github might work in tandum in some places, they do not mock one anothers behavior.

**Comment by borekb** [comment]
Ah, sorry, I read this in the wiki (emphasis mine):

> The jekyll/jekyll:pages, and jekyll/builder:pages tags try to be as close to Github pages as possible, without changing much, there might be some differences and if there are **please do file a ticket** and they will be corrected if possible...

Maybe the wording should be updated if the projects are too far apart (I'm now reading about GH Pages and they indeed have quite a few specific features; I've tried several other "GitHub Pages" containers and most of them don't work either).

**Comment by envygeeks** [comment]
I will update it so it's more clear! Can you name a few of those features? Some features we would like to support as we can, some features (like the one you just requested) are out of scope of this image and either belong to Jekyll (who can fix it easily actually and if you file a ticket there I'll happily fix it since it's my code that does this) and some features are important as they would hinder your development if they don't exist.

**Comment by borekb** [comment]
I'm a newbie when it comes to Jekyll and GH Pages, sorry if some things I sense don't make sense or don't belong to the right project. What seems to be unique to GH Pages based on [this blog post](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3):

- `index.md` instead of `index.html`
- Even `README.md` is accepted so a default GitHub repo with just this file is a valid Pages site.
- There's a default, GitHub-like theme if a theme is not specified in `_config.yml`
- Layout is assigned automatically if it's not specified
- Front matter doesn't need to be present
- Some automatic H1, H2 and H3 parsing.
