### ISSUE TITLE
Failures pulling envygeeks mirrors

### ISSUE THREAD

**Issue by jdwilly2001** [jekyll/docker#156]
I am using this container within a build pipeline. I am getting occasional failures when running **apk  update** command in preparation to install packages. 

I noticed that this was built from envygeeks/alpine and not from alpine directly. 

Do you have a version which uses the mainline alpine?

Attaching error message and command
`+ apk update && apk add py-pip python-dev && pip install awscli
fetch http://mirror.envygeeks.io/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/v3.5/main: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.b1f0b368.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/v3.5/community: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.a8c7bf4a.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/edge/community: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.49e8d556.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/edge/testing: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.343bec1d.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/edge/main: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.b6beb1b8.tar.gz: No such file or directory
5 errors; 72 distinct packages available`

**Comment by ehaselwanter** [comment]
me too.

```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p $(docker-machine ip `docker-machine active`):4000:4000 jekyll/jekyll jekyll serve
No active host found
Error: No machine name(s) specified and no "default" machine exists
fetch http://mirror.envygeeks.io/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/v3.5/main: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.b1f0b368.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/v3.5/community: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.a8c7bf4a.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/edge/community: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.49e8d556.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/edge/testing: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.343bec1d.tar.gz: No such file or directory
fetch http://mirror.envygeeks.io/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://mirror.envygeeks.io/alpine/edge/main: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.b6beb1b8.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  imagemagick (missing):
    required by: world[imagemagick]
```

**Comment by envygeeks** [comment]
This should be fixed now.

**Comment by steveoh** [comment]
It's happening again.

**Comment by envygeeks** [comment]
Hey @steveoh,

Our images haven't used that mirror since August 30th https://github.com/jekyll/docker/commit/297f0849242ba44d192f84266f27c49252911f19 please update your images as it was removed and left for a month (to give people time to update before it was shutdown) because it was costing too much money ($1200 a month,) and because Alpine now has proper CDN's to carry it's packages.
