### ISSUE TITLE
Permission issues with newer jekyll docker images

### ISSUE THREAD

**Issue by tlbdk** [jekyll/docker#178]
I have been using the jekyll/builder:3.5 image without issue it was updated recently and all of a sudden the gem installation when running jekyll build failes with permissions errors:

```
Install missing gems with `bundle install`.
There was an error while trying to write to `/usr/local/bundle/config`.
````

Running bundle install manually works without issue:

```
bundle install
jekyll build -q --destination $DESTINATION
```

Is the jekyll command dropping privileges when running bundle in some newer versions?

**Comment by envygeeks** [comment]
Indeed we do drop privileges when running the bundle command, but we've always done that, however, I  also changed the way some of our stuff behaves to make it a tiny bit more strict (in-fact it's way more strict now,) which might be what's causing the problem.  I think I drop privileges much earlier than before.  Is your repository open source (fine if it's not) and can you provide the command you use.

**Comment by tlbdk** [comment]
Currently the docker repo it is not open source as it is in with other things that need a bit of clean up before we can do that:

But the short version is a docker file with:

‘‘‘
FROM jekyll/builder:3.5

... Copy the shell script in, etc

CMD ["/usr/local/bin/init.sh"]
‘‘‘

The init.sh script does a bit more but the:

‘‘‘
...
bundle install
jekyll build -q --destination $DESTINATION
‘‘‘

The site we are building is here:
https://github.com/connectedcars/connectedcars.github.io

Would it be possible to not install the gems globally but in the same directory as the build?

**Comment by envygeeks** [comment]
https://github.com/jekyll/docker#config

**Comment by jgmize** [comment]
We ran into this same problem. Here is a jenkins log of the error: https://ci.us-west.moz.works/blue/organizations/jenkins/irlpodcast/detail/master/33/pipeline/
Here is the source of the command that is now failing: https://github.com/mozilla/irlpodcast/blob/master/bin/build.sh

**Comment by jgmize** [comment]
Part of the problem for us is that all of the [image tags](https://hub.docker.com/r/jekyll/jekyll/tags/) appear to have been updated at once, so we can't just switch to a previous version of the image.

**Comment by envygeeks** [comment]
@jgmize I'm working on this problem right now, thanks for the logs they will surely help me get this fixed in the next hour or so.  Right now we do update all tags at once, but I'm reworking our build process so we behave more inline with other Docker images where we only build the latest version, the reason I opted for this build format is because of security issues that might arise.

**Comment by jgmize** [comment]
thanks for the quick response @envygeeks

**Comment by tlbdk** [comment]
Seems the fix completely disabled automatic bundle install on jekyll build:

I have added 'bundle install --quiet' before my jekyll build command to make it work.

``` 
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find autoprefixer-rails-6.3.7 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
