### ISSUE TITLE
Dependency error: jekyll-seo-tag

### ISSUE THREAD

**Issue by ulope** [jekyll/docker#179]
Trying to use either `jekyll/jekyll` or `jekyll/builder` results in:

```
Dependency Error: Yikes! It looks like you don't have jekyll-seo-tag or one of its dependencies 
installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error 
message from Ruby is: 'cannot load such file -- jekyll-seo-tag' If you run into trouble, you can find 
helpful resources at https://jekyllrb.com/help/!
```

Command used: 
`docker run --rm -it --entrypoint jekyll -v /data:/data jekyll/builder build -s /data`

Image versions:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jekyll/builder      latest              e22dc2098bdf        11 hours ago        376MB
jekyll/jekyll       latest              07f0648f3147        11 hours ago        355MB
```

**Comment by ulope** [comment]
Ok that was a dependency from the content. Sorry for the noise.

Still it would be nice if there was an easy way to specify additional gems that are needed without having to rebuild the image or manually doing so inside the container before building.

**Comment by envygeeks** [comment]
There is, it's called a Gemfile.
