### ISSUE TITLE
Incomplete instructions for installing additional packages 

### ISSUE THREAD

**Issue by asarkar** [jekyll/docker#181]
README says:

> You can install system packages by providing a file named .apk with one package per line.

I know what an `.apk` file is, but I don't understand how do I provide one to the container. Please be specific with instructions.

**Comment by envygeeks** [comment]
Put it in your Jekyll folder, if you were supposed to have put it somewhere else I would have said so, as I do with all other directions...

**Comment by asarkar** [comment]
@envygeeks You didn't say to put it in the Jekyll folder either, but only some mumbling about "provide" an apk file. Thanks anyway.

**Comment by envygeeks** [comment]
That should have been obvious.  Actually not should have been, it is.

**Comment by asarkar** [comment]
It is obvious if you're in the business of palm reading and crystal ball gazing, which I'm not. Can't speak for you.
