### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by Djabx** [jekyll/docker#182]
Hi,

According to the README.md, I'm doing this:

```
export JEKYLL_VERSION=3.5
docker run --rm \
  --volume=$PWD:/srv/jekyll \
  --volume=$PWD/vendor/bundle:/usr/local/bundle \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  jekyll build
```

And have this as a result:
`ruby: No such file or directory -- serve (LoadError)`

After geting in the docker, the `--volume=$PWD/vendor/bundle:/usr/local/bundle` line seams to hide all ruby tools (like jekyll script).

Should the line be ` `--volume=$PWD/vendor/bundle:/usr/local/bundle/cache` ?

**Comment by Djabx** [comment]
well... it does not work either.

Any idea how can we skeep the download / install of bundle every time we want to test our blog ?

**Comment by envygeeks** [comment]
Please update your image, this issue was fixed yesterday.
