### ISSUE TITLE
Rewrite docker-compose.yml

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker#189]
- [ ] Remove caching by default.
- [ ] Make sure the `new` command doesn't use a prefix.
- [ ] Change the service names.

**Comment by arthur24b6** [comment]
I think the version number is still needed in the `docker-compose.yml` file. If I run it without out, I get:
```$ docker-compose run --service-ports site jekyll s
ERROR: The Compose file './docker-compose.yml' is invalid because:
```
Adding `version: '2'` to the file allows it to run for me.

**Comment by envygeeks** [comment]
This ticket had nothing to do with that, please file a ticket if you have an issue rather than commenting on a closed ticket expecting a resolution on an already rejected solution.

Thanks!
