### ISSUE TITLE
ERROR: http://mirror.envygeeks.io/alpine/v3.5/main: DNS lookup error

### ISSUE THREAD

**Issue by micheltol** [jekyll/docker#193]
Hi,

I am using the following docker-compose.yml file

> version: '2'
> services:
>   site:
>     command: jekyll serve
>     image: jekyll/jekyll:builder
>     volumes:
>       - .:/srv/jekyll
>       - ./vendor/bundle:/usr/local/bundle
>     ports:
>       - 4000:4000
>       - 35729:35729
>       - 3000:3000
>       -   80:4000

Trying to run the following commands to create my new site:

> docker-compose run site jekyll new site

This fails with the following errors:
C:\projects\jekyll\test2>docker-compose run site jekyll new site
ERROR: http://mirror.envygeeks.io/alpine/v3.5/main: DNS lookup error
ERROR: http://mirror.envygeeks.io/alpine/v3.5/community: DNS lookup error
ERROR: http://mirror.envygeeks.io/alpine/edge/community: DNS lookup error
ERROR: http://mirror.envygeeks.io/alpine/edge/testing: DNS lookup error
ERROR: http://mirror.envygeeks.io/alpine/edge/main: DNS lookup error

Am I missing anything, how can I resolve this issue?

tnx!

**Comment by micheltol** [comment]
Spending 4 hours on an issue yourself, writing 1 single post on Github and 2 minutes later you find the problem youself. 
I was using the wrong image :)
It should be image: jekyll/builder:latest

**Comment by mattr-** [comment]
Glad you were able to figure it out on your own. :smiley:

**Comment by envygeeks** [comment]
We might have a build problem, we should be aliasing `jekyll/jekyll:builder` to `jekyll/builder:latest` at build time, as for the DNS resolution error, we removed that almost 6 months ago when the bill for the mirror got too high, so we reverted to Alpine's mirror when they finally got funding to get a CDN.
