### ISSUE TITLE
Installing Gems

### ISSUE THREAD

**Issue by johnjelinek** [jekyll/docker#2]
How should I install gems in my container? Do I need to do a `bundle install` prior to a `jekyll build`?

**Comment by envygeeks** [comment]
It depends on how you want to do it there are two ways you can do it:

***Via your own private image (persistence across all your future projects):***
```Dockerfile
FROM jekyll/jekyll:ubuntu-stable
RUN gem install <mygem> && \
  rm -rf /opt/jekyll/lib/ruby/gems/2.2.0/cache/* && \
  gem clean
```

```sh
docker build -t username/jekyll:ubuntu-stable
docker run --name jekyll -p 127.0.0.1:4000:4000 \
  -v $(pwd):/srv/jekyll -dt username/jekyll:ubuntu-stable
docker start jekyll
# docker stop jekyll
# docker rm -fv jekyll
```

**Or as a temporary addition to our image with temporary persistence***
```sh
docker run --name jekyll -p 127.0.0.1:4000:4000 \
  -v $(pwd):/srv/jekyll -dt jekyll/jekyll:ubuntu-stable
docker exec jekyll sudo -u root gem install <mygem>
docker run jekyll
# docker stop jekyll
# docker rm -fv jekyll
```

***You can also just straight up use Bundler without needing to do anything special on the system:***
```sh
docker run --name jekyll -p 127.0.0.1:4000:4000 \
  -v $(pwd):/srv/jekyll -dt jekyll/jekyll:ubuntu-stable
docker exec bundle install --path vendor/bundle
docker start
```

The bundler method will install it inside of your volume which should be the local folder (on your system not on docker) that you mounted to `/srv/jekyll` (on the docker image) and will write it as the user jekyll(1000) (the most common base user on Linux systems.)

**Comment by envygeeks** [comment]
I stripped out the bundler method, I forgot that because it's a system wide install and we shiv `/usr/bin/jekyll` for you that it wouldn't provide you the benefits we give you via that shiv so it's best to just system install it.
