### ISSUE TITLE
Build a Docker super image.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker#3]
Build a docker super image that allows people to deploy with Docker compose and supports git pushing and automatic building with an Nginx proxy in the front and Jekyll always running in the background waiting for changes to build to the Nginx instance so people can have Github like building in production without complicated setups.

**Comment by parkr** [comment]
:+1:

**Comment by jhabdas** [comment]
Here's an [example Dockerfile](https://gist.github.com/jhabdas/e0d5e3bed0316f1a5783) which hosts Jekyll under Docker and serves it up using Nginx via Phusion Passenger. There are methods for zero-downtime deploys out there which feels like an important use case to cover, more so than auto-regen IMHO. But the idea of a more fully-featured sandbox feels like it could be useful so long as it remains extensible. Thoughts?

**Comment by envygeeks** [comment]
I absolutely refuse to use the Phusion passenger image (for reasons that I will keep to myself on this ticket system lest I start a war that I don't want to start.) To address the "0-downtime" issue -- there is and will not be any restart because this image will only support the github dependencies and you'll need to fork if you want other dependencies so there will be no downtime... and if there is that's the fault of your underlying file system when the folder is overwritten (which means you have big issues with your hardware.) 

Server 
   | -> Nginx
   | -> Watcher (Git process / SSH - whatever we choose)
      | -> Jekyll -> Watch -> Generate
      | -> Overwrite entire directory all at once.

**Comment by envygeeks** [comment]
In essence you'll have duplicated source, one live and one that is constantly watched and generated and synced over to the live source once it's ready and done processing.

**Comment by jhabdas** [comment]
You've piqued my interest, but let's not go there ^^. My current
build-deploy process is down to shell 5 commands. Perhaps something
lightweight like [deploy](https://github.com/visionmedia/deploy) could
smooth things out. Or perhaps more on point is the octopress-deploy gem.

**Comment by jhabdas** [comment]
FWIW I'm using s3_website Gem now to deploy site sans Docker and Nginx, with cloudfront CDN enabled in a few LOC

**Comment by envygeeks** [comment]
Want to file a feature ticket @jhabdas I'm happy to add it to the builder image if it's quick and easy.
