### ISSUE TITLE
Container does not respond to SIGTERM

### ISSUE THREAD

**Issue by pwaller** [jekyll/docker#33]
The effect is that `docker stop` is slow, since it waits 10 seconds before killing the container.

This is making a poor user experience when using `jekyll` with `docker-compose`, since it will sit there for 10 seconds waiting for jekyll to exit. (meanwhile the rest of our infrastructure has torn down for 10 seconds).

I guess what is happening is that `startup` is ignoring or otherwise not responding quickly to `SIGTERM`. If I do `docker exec <container> kill -TERM 1` it indeed does not shut down.

**Comment by pwaller** [comment]
I've just discovered a workaround which works for me, which is to use `--entrypoint jekyll`, since I don't need any services running anyway. This means that jekyll gets the SIGTERM and exits promptly.

**Comment by envygeeks** [comment]
https://github.com/envygeeks/docker/blob/master/vendor/common/usr/local/bin/startup#L31 your assumptions are incorrect, please provide more information because we do respond to term.

**Comment by pwaller** [comment]
The problem can be seen if you do the following:

In one window, run:

```
$ docker run --name jekyll -ti --rm jekyll/jekyll
```

In another, run this:

```
$ time docker stop jekyll

real	0m10.267s
user	0m0.032s
sys	0m0.016s
```

Note that it takes 10 seconds, I believe because the TERM signal has been ignored. If you do `docker kill`, it is instant.

You can also see the problem if you do:

```
$ docker exec jekyll kill 1
```

You'll see that it doesn't stop.

**Comment by envygeeks** [comment]
It turns out we expected default to trap itself but we shouldn't do that so now we usurp any traps it might do and issue a kill on it's behalf if it does an `exec`.  Once Travis finishes building envygeeks/alpine and envygeeks/ubuntu Docker Hub will reissue this image with the fixes.

Thanks for the ticket!
