### ISSUE TITLE
Autoreload issue boot2docker on OS X

### ISSUE THREAD

**Issue by bilby91** [jekyll/docker#37]
Hello guys,

Is the autoreload issue with boot2docker also happening in OS X ? I had to add the `--force_polling` flag to enable rebuilt when a file has been changed.  

I'm asking this because the documentation states that the issue only happens on Windows.

Thanks!

**Comment by envygeeks** [comment]
Yessir, that is the case, I should have probably noted that too, I'll leave this open to remind me to update the documentation when I go through my backlog and fix issues!

Thanks.
