### ISSUE TITLE
sendfile causing issues

### ISSUE THREAD

**Issue by braderhart** [jekyll/docker#41]
I'm using the Jekyll Docker image using Docker Toolbox which uses VirtualBox. I'm using shared folders and the folder I have set as my source is a share on my Windows host that I am mounting inside my Jekyll container. This is causing the following issue:

https://www.virtualbox.org/ticket/9069

Can you turn sendfile off in NGINX by default, or at least provide an easy way to change this setting? Any ideas?

**Comment by parkr** [comment]
Just to be clear, you're having issues with serving your site using the Docker images?

**Comment by envygeeks** [comment]
I thought they fixed that damn bug years ago.  I went ahead and disabled sendfile until I could come up with an elegant solution to allowing you to customize that location directly with our `.nginx` folder.

**Comment by braderhart** [comment]
Thank you for your quick response. This sort of fixes the issue I'm having, although more info can be found here:

https://github.com/boot2docker/boot2docker/issues/1069#issuecomment-149051114
