### ISSUE TITLE
Pry gem is not there

### ISSUE THREAD

**Issue by iBobik** [jekyll/docker#45]
In README there is "pry" gem, but I did not found it in opts.
https://github.com/jekyll/docker/blame/master/README.md#L45

**Comment by envygeeks** [comment]
You are the reason for that: https://github.com/jekyll/docker/commit/db0d6e7bac17c7bb60bdc39c76693f70f715dbfc you regressed it.

**Comment by envygeeks** [comment]
I feel the need to apologize for being terse, I wasn't trying to be mean, I was in the middle of something so a terse response happened, I reverted the regression and re-removed pry from the list!

**Comment by iBobik** [comment]
Ouch! :-)



Jan Pobořil

2015-10-18 19:29 GMT-05:00 Jordon Bedwell <notifications@github.com>:
