### ISSUE TITLE
Remove nginx from builder

### ISSUE THREAD

**Issue by iBobik** [jekyll/docker#46]
Because we split building image to separated tag, how about to remove parts not needed there? Nginx is the first.

**Comment by envygeeks** [comment]
I'll consider over the next few days it but unless there proof it has an impact on performance it's probably gonna stand at a hard no because it provides more benefit there than it does on it's own tag.

**Comment by envygeeks** [comment]
I actually read this ticket wrong.  I thought it said all images but I re-read it.

**Comment by iBobik** [comment]
It seems something rely on nginx:

```
$ docker run -it jekyll/jekyll:builder /bin/sh
/srv/jekyll # ./run: exec: line 11: nginx: not found
./run: exec: line 11: nginx: not found
./run: exec: line 11: nginx: not found
./run: exec: line 11: nginx: not found
./run: exec: line 11: nginx: not found
```
