### ISSUE TITLE
Builder: Bash and openssh-client missing

### ISSUE THREAD

**Issue by iBobik** [jekyll/docker#48]
Bash and openssh-client APK packages are not in config file: https://github.com/jekyll/docker/blob/master/opts.yml#L14
but is is not in generated Dockerfile: https://github.com/jekyll/docker/blob/master/tags/builder/Dockerfile#L13

Result is:
```bash
$ docker run -it jekyll/jekyll:builder /bin/bash
/usr/local/bin/startup: line 67: /bin/bash: not found
```

**Comment by deedoubledub** [comment]
I believe there has been a regression of this bug. I am using jekyll/jekyll:builder with gitlab-ci and I am seeing the following today. The previous build, on December 7, did not exhibit this behavior. I see the same output when manually executing ```docker run -it jekyll/jekyll:builder /bin/bash```.

```
/usr/local/bin/startup: line 67: bash: not found
ok: down: /etc/startup3.d/nginx: 0s, normally up
```

**Comment by envygeeks** [comment]
Please file a new ticket, commenting in old tickets is not considered a report.  Thanks.

**Comment by envygeeks** [comment]
I've repushed a fixed version @deedoubledub, I forgot that alias builders weren't completed on the beta-version of Docker Template when I kicked on Alias building so it was never actually getting built with the alias merging it was simply being aliased literally to 3.0.1, now it's own it's own build chain again until that feature is finished upstream.  Sorry for the mistake.
