### ISSUE TITLE
Create an Octopress image.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker#5]
If @imathis is fine with us distributing an Octopress image on his behalf.  Somebody asked me about it today and I'm fine with doing it if Octopress is fine with us doing it.

**Comment by envygeeks** [comment]
I'd even be happy to do it directly on Octopress and on an Octopress Docker Hub account.

**Comment by imathis** [comment]
Oh sorry, I just saw this. I have no experience with Docker, but I'd love to make it possible for people to use Octopress with it. The current version at [imathis/octopress](https://github.com/imathis/octopress) not so much (as I'm not going to be supporting that with the release on 3.0), but I'd love for people to be able to easily use the new gems under the [octopress org](https://github.com/octopress). What does this entail?

**Comment by envygeeks** [comment]
It doesn't really require you to do anything other than setup a repo and give me write access and I'll build it or... we can build it here but Octopress isn't necessarily an official Jekyll project so it should probably be done on Octopress.

**Comment by imathis** [comment]
I've created [octopress/docker](https://github.com/octopress/docker) and added you as a collaborator with write access. I'm excited to see what you do please let me know where i can help.

**Comment by envygeeks** [comment]
Tracking this there!
