### ISSUE TITLE
Could not find celluloid-0.16.1 in any of the sources

### ISSUE THREAD

**Issue by kelunik** [jekyll/docker#52]
Running `jekyll/jekyll:pages` fails with the following error:

```
Executing busybox-1.23.2-r9.trigger
OK: 265 MiB in 74 packages
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find celluloid-0.16.1 in any of the sources
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
OK: 265 MiB in 74 packages
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find celluloid-0.16.1 in any of the sources
```

Celluloid 0.16.1 was yanked, see http://stackoverflow.com/q/32182273/2373138. Either 0.16.0 or 0.17.x has to be used.

**Comment by envygeeks** [comment]
That's a problem with your dependencies not ours. Sorry.

**Comment by envygeeks** [comment]
If you want to post more information to https://talk.jekyllrb.com I'll gladly help you sort out your gems.

**Comment by kelunik** [comment]
What's the additional information you need? That's the command I ran:
`docker run --rm --label=jekyll -v=$(pwd):/srv/jekyll -ti -p 127.0.0.1:4000:4000 jekyll/jekyll:pages`

**Comment by kelunik** [comment]
It's working now without any changes.
