### ISSUE TITLE
Gemfile.docker

### ISSUE THREAD

**Issue by kelunik** [jekyll/docker#53]
Why does it rename `Gemfile` to `Gemfile.docker` while it's running? This makes committing harder than it should be, because you always have to shutdown the container before committing, otherwise Git will add the rename into the history.

**Comment by envygeeks** [comment]
The message given literally tells you why. Whether or not we rename a file and change it back has no affect on your git history unless you make it affect it, we do mess with your Git.  You are improperly shutting down if it is not changed back.

**Comment by kelunik** [comment]
It does change it back, but I want to commit and keep it running.

**Comment by envygeeks** [comment]
None of what we do stops you from committing anything so what's the problem?

**Comment by kelunik** [comment]
While it's running it's `Gemfile.docker`, so I can't use `git add .` safely to commit all changes, because the rename isn't an actual change that should be committed.

**Comment by envygeeks** [comment]
While I always think it's bad policy to `git add .` I do it all the time too so I understand the frustration.  No promises on fixing quickly (within the next couple of days) but I'll take a look at it and see what I can do about optimizing it.

**Comment by kelunik** [comment]
Why should that be bad policy? As long as you do not update multiple things and don't want to commit them in one commit, I think it's just fine. No hurry. :-)

**Comment by envygeeks** [comment]
Because it leads to implicit mistakes like adding something that should be in the `.gitignore` but isn't, it's not noticed, it's added, which might only happen every couple of years if at all, but it can happen.  There are also other reasons but those don't matter as much as the implicit mistake.
