### ISSUE TITLE
github certificate authority not trusted?

### ISSUE THREAD

**Issue by catherinedevlin** [jekyll/docker#54]
Currently, my attempts to run the image are failing with

    Fetching https://github.com/jekyll/jekyll-archives.git
    fatal: unable to access 'https://github.com/jekyll/jekyll-archives.git/': error setting certificate verify locations:
      CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: none

and several more errors along those lines.  I think this means that github is now using a certificate not recognized in the cert authorities built into the base image, but I'm not sure.

**Comment by envygeeks** [comment]
That seems weird, AFAIW Github still uses the same certificate and we've not updated our images.  @benbalter is there anybody you can get to confirm or deny this so we can test it and file a ticket upstream if need be?

**Comment by spraints** [comment]
Certs aren't my forte, but it looks like they haven't changed in over a year, so my guess is that that's not the problem. @catherinedevlin - what command are you running that leads to that error?

**Comment by dhcole** [comment]
It looks like this happens when using a site with a dependency in the Gemfile that uses the https endpoint, like this: https://github.com/18F/18f.gsa.gov/blob/staging/Gemfile#L11

**Comment by envygeeks** [comment]
@dhcole perfect, I'll fork that source and see if I can work out the problem tonight.

**Comment by dhcole** [comment]
Thanks @envygeeks! Just confirming I was able to replicate this with a simple test case, using [18F/18f.gsa.gov](https://github.com/18F/18f.gsa.gov)

```bash
$ docker run --rm --volume=$(pwd):/srv/jekyll jekyll/jekyll:builder jekyll build
```

```bash
...
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/jekyll/jekyll-archives.git
fatal: unable to access 'https://github.com/jekyll/jekyll-archives.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
...
```
