### ISSUE TITLE
Add tags for exact Jekyll versions

### ISSUE THREAD

**Issue by iBobik** [jekyll/docker#55]
As suggested in jekyll/jekyll#4118:
> Also @jekyll/docker should allow fixing to major version by tag as usual in
other images (good example is PHP <https://hub.docker.com/_/php/>),
currently it allows fixing only to relative versions. (If I use „builder“
tag, I it means „stable“ Jekyll version and it means that in some time my
site will be broken if I do nothing.)

**Comment by envygeeks** [comment]
This is a `WONT FIX` until Docker hub gets their act together.  I love Docker with all my heart but Docker Hub is a terrible mess and until they allow us to delete tags so I don't have 5 million versions laying around and 5 million tags wasting data on their servers that could be potential security disasters I'm a definite no on this.

**Comment by envygeeks** [comment]
To add: If you are wanting to still have access to 2.5 after I finally update this repo to 3.0 you will be allowed to do that as I plan to add an oldstable tag that will maintain the last back major version the same way that Debian does.

**Comment by iBobik** [comment]
Yea, but it is needed to allow fixing version somehow.

What about to just add tags for just major versions? (2, 3)

It is also important to have tag for absolute version, not relative (like
„stable“ or „oldstable“), because is is good to keep old version deployed
without need intervention always when there is new release.



Jan Pobořil

2015-11-09 21:37 GMT-06:00 Jordon Bedwell <notifications@github.com>:

**Comment by iBobik** [comment]
Btw, tags for versions seems like best practice for Docker images and is
widely adopted. In not seems somebody cares about growing tags amount for
historic versions on Hub. (You don’t need to have it in repo, they just
lays on Hub as a build.)



Jan Pobořil

2015-11-09 21:44 GMT-06:00 Jan Pobořil <bobik@ibobik.cz>:

**Comment by iBobik** [comment]
Good work. But there is one lack - major version tags are not for builder.

**Comment by envygeeks** [comment]
I made the very explicit decision after long thought while doing this to *not support* any version that is not the latest version for the builder tag, it will always be the latest, I have no plans to revert that decision as there is no compelling reason to do so.

**Comment by iBobik** [comment]
Consistency with Docker best practices (what are their reasons) is not
compelling
reason?



Jan Pobořil

2015-12-06 20:07 GMT+01:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
That's not a best practice, the best practice is `jekyll/jekyll:3.0` or `jekyll/builder:3.0` not `jekyll/jekyll:builder-3.0` the tag is a helper that adds extras for you and it will always be the latest version.

I am not unreasonable though, I'll come back and reconsider what you wish when I have time to split this single repo into multiple repos where builder is it's own repo on the Docker Jekyll org (if I decide to) at that point then I can and will maintain older versions.

**Comment by iBobik** [comment]
Yes, propably it will be good to make a second repo on Hub. Source Github
repo can be the same, Hub can build both repos from one.

Best practice is to provide tags for major, decimal and minor (if used in
project) versions separately, because some users needs to fix only major
version, some of them needs decimal version. So there should be tags e.g.
`3`, `3.0`, `3.0.1`, `2`, `2.5`, `2.5.4`.



Jan Pobořil

2015-12-06 21:47 GMT+01:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
Please stop treating me like I'm dumb.  I know how to Docker.

**Comment by iBobik** [comment]
Sorry, no offense. Just trying to help.



Jan Pobořil

2015-12-06 22:18 GMT+01:00 Jordon Bedwell <notifications@github.com>:
