### ISSUE TITLE
provide Dockerfiles for Jekyll 3.x (it's stable now)

### ISSUE THREAD

**Issue by nkuehn** [jekyll/docker#58]
We would very much like to work with the builder and other variants of these Dockerfiles, but as we are using Jekyll 3.0.0  we can only use the "beta" one.  

As there seems to be an issue with GitHub tags ( see  #55  )  you could provide additional built variants like  "builder3"  "latest3" etc.  (or some other naming convention).

**Comment by envygeeks** [comment]
This is planned to be fixed today or tomorrow as it's dependent on our build software to be finished (not Jekyll's but the upstream build software that organizes this repo.) Once that's completed everything will finally be updated and latest will be an aliased of stable will be an alias of 3.0 and builder will update to 3.0, we will not provide legacy versions for named tags except for the "old-stable" (or "old" -- I've yet to settle on that name.)

The issue you linked to is technically a non-issue and was never a blocker, the blocker was the upstream builder that organizes our repository, it was under going a rebuild and it is going open-source so this repo is blocked by that and it was set to be finished yesterday but I decided to audit the source once last time before making it officially public.

**Comment by nkuehn** [comment]
great!
