### ISSUE TITLE
/usr/bin/jekyll overrides config settings

### ISSUE THREAD

**Issue by Juev** [jekyll/docker#6]
The file that is added to the image contains a call jekyll with parameter -s, which overrides the settings specified in the configuration file.

For example site [Juev/juev.org](https://github.com/Juev/juev.org). Source is located in directory 

    juev.org/source 

And when you try to compile the project get a lot of errors.
If this file is deleted, the assembly of the project is proceeding normally.

**Comment by envygeeks** [comment]
You can send the `-s` option and override our `-s` or you can mount to `/srv/jekyll` as recommended.

**Comment by envygeeks** [comment]
As of today, just to be sure you can override we also try to detect "-s" now, this is just a double assurance to make sure that you want to do gets completed without much trouble from us.
