### ISSUE TITLE
Enable build watch via an environment variable

### ISSUE THREAD

**Issue by behemphi** [jekyll/docker#60]
I am new (hours) to Jekyll, so this might be an inappropriate ask.

I am using the `jekyll:pages` container and it beautifully serves my budding site.  Thanks a _bunch_!

My problem lies in that any change I make to the site content (add a post, change the index, etc) forces me to kill and start a new image.  (i.e. start a new container)

My goal would be to have the run time of this container, in a "development" mode, use the `build --watch` feature so that when I make changes on my workstation they are reflected in real time via the browser serving from the container.

Something like this for a docker run command:

```
docker run \
  --env JEKYLL_INTERACTIVE_DEVELOPMENT=0  # <- This is the addition
  -it \
  --rm \
  --label=jekyll 
  --publish $(docker-machine ip jekyll):4000:4000  \   
  --volume=$(pwd):/srv/jekyll \
  jekyll/jekyll:pages jekyll serve
```

I have looked through the `Dockerfile` and looked through the `runsvdir` directories in a running container and don't see any code for this. 

I would suggest a script like the following that would be enabled only if the suggest env var is set to true (0). 

```sh
#!/bin/sh
set -e 

# If the environment variable is unset, then give it a value.
if [ -z $JEKYLL_INTERACTIVE_DEVELOPMENT ] 
then
	JEKYLL_INTERACTIVE_DEVELOPMENT=1
fi

# If the user set the environment variable to 0 so they could work interactively
# then run have `jekyll build` watch for changes in the mounted directory
if [ $JEKYLL_INTERACTIVE_DEVELOPMENT -eq 0 ]
then 

	cd /srv/jekyll
	exec jekyll build --watch --future --unpublished --verbose --force_polling
	
fi
```

I put this in `/etc/startup2.d/jekyll_build/run` and got the described result.

Thanks for the consideration.

**Comment by envygeeks** [comment]
What are you trying to achieve? What you hacked in as a script can already be done by just changing the `jekyll serve` bit on the your command to `jekyll build --watch --future` and all that, so my question really is what benefit does this provide over and beyond that?

**Comment by parkr** [comment]
@behemphi I think your command could be:

```bash
docker run \
  -it \
  --rm \
  --label=jekyll 
  --publish $(docker-machine ip jekyll):4000:4000  \   
  --volume=$(pwd):/srv/jekyll \
  jekyll/jekyll:pages \
  jekyll build --watch # <-- here's the watch you're looking for
```

**Comment by envygeeks** [comment]
Now you can do:

```
docker run --rm --label=jekyll -P 4000:4000 -e VERBOSE=true -e POLLING=true \
  --volume=$(pwd):/srv/jekyll
```

We've kicked on `--future` and `--unpublished` in dev and added support for quick verbosity and polling with our default command (or actually technically with any Jekyll command since it went on our Jekyll shiv directly.)

**Comment by behemphi** [comment]
@envygeeks I was trying to achieve precisely what you provided.  Thank you!  

For anyone who lands here ... the command that ultimately worked for me was this:

```
docker run \
  --env FORCE_POLLING=true \
  --env JEKYLL_ENV=development \
  --env VERBOSE=true \
  --interactive \
  --label=jekyll \
  --tty \
  --publish $(docker-machine ip jekyll):4000:80 \  
  --rm \  
  --volume=$(pwd):/srv/jekyll jekyll/jekyll:pages \
   jekyll build --watch
```

Some comments:

* My entire focus here is using the running container as a development environment. I have no intention of running in a "production" environment.
* I have to enable `FORCE_POLLING` to have the site regenerate on save.  To be clear, I am saving on my workstation and using the nginx runtime from the container.  I suspect this might be something to do with the way the file system is mounted to the container.
* It is ideal to have `VERBOSE` enabled when running the container in `--interactive` mode. This provides a real time spool on each save to indicate something happened in the run time.  Suspect I won't care so much after I learn to trust it.
* Above, @parkr took the time to provide a command. The command appears need to have the port mapping (`--publish`) of IP:4000:80 rather than IP:4000:4000. See #61 for more.

I appreciate the stunning quick and thorough response folks!
