### ISSUE TITLE
jekyll/jekyll:2.5 runs jekyll 3.0.1

### ISSUE THREAD

**Issue by tomassommar** [jekyll/docker#61]
When pulling and running jekyll/jekyll:2.5 one would expect jekyll version 2.5. But the image actually runs jekyll 3.0.1

Reproduce: 
````
docker run -it jekyll/jekyll:2.5  /bin/sh
jekyll --version
```
Prints out Jekyll 3.0.1.

**Comment by envygeeks** [comment]
It's because of `jekyll-mentions`; I'll issue a hotfix and lock the last release of `jekyll-mentions` that supports 2.5, sorry about this -- see: https://github.com/jekyll/docker/issues/61

**Comment by tomassommar** [comment]
Thanks!
