### ISSUE TITLE
jekyll new -> invalid option: --future

### ISSUE THREAD

**Issue by devcrafting** [jekyll/docker#65]
Hi,

I am trying to use the docker image jekyll/jekyll:pages to bootstrap a jekyll GitHub pages site.
When I run :

     docker run --rm -ti --label=jekyll --volume=$(pwd):/srv/jekyll -p 4000:4000 jekyll/jekyll:pages jekyll new . --force

it returns :

    jekyll 2.5.3 | Error:  Whoops, we can't understand your command.
    jekyll 2.5.3 | Error:  invalid option: --future
    jekyll 2.5.3 | Error:  Run your command again with the --help switch to see available options.

Can't find what goes wrong...I searched for --future invalid option for jekyll, but nothing found but a reference to a bug in 2.x version with --future flag : http://jekyllrb.com/docs/upgrading/2-to-3/

What's wrong ? Thanks.

Clément

**Comment by envygeeks** [comment]
You've done nothing wrong, I have a bug in my shim, I'll release a fix for you after I test another bug discovered while working on this bug.

**Comment by envygeeks** [comment]
Even  though the commit was never made my build server pushed out a fix last night for you, the reason a commit was never made as there were dozens of other changes in the works to make this repository more robust for people who need more flexibility.

Either way I'm gonna hold this open until I make that commit but a push was made last night.

**Comment by devcrafting** [comment]
Perfect ! It works. Thanks
