### ISSUE TITLE
Tag pages not found in repository jekyll/jekyll

### ISSUE THREAD

**Issue by Baughn** [jekyll/docker#66]
Indeed, it doesn't seem to exist. It's still references in the README, however.

```
➜  website git:(master) docker pull jekyll/jekyll:pages
Pulling repository jekyll/jekyll
FATA[0003] Tag pages not found in repository jekyll/jekyll 
```

**Comment by envygeeks** [comment]
They are still referenced because they were only deleted to do a reset of some stuff. They've been gone less than an hour.
