### ISSUE TITLE
Set up automated builds on Docker Hub

### ISSUE THREAD

**Issue by mchelen** [jekyll/docker#7]
Docker Hub can use automated builds which are based on the latest Dockerfile commit.
http://docs.docker.com/docker-hub/builds/

**Comment by parkr** [comment]
That's cool!

**Comment by envygeeks** [comment]
It's a neat feature but I don't think we'll be using it anytime since Hulk/Skynet (the builders that currently handle publishing) self bootstrap to build our debs when they build the image.  That's not possible with Docker Hub.

**Comment by envygeeks** [comment]
After thinking about for a long time I think I will set it up so we can have automatic builds but that won't come until I finish working out some of the basics of how we want the images to behave on a final level as even though they are released (and I do use them in production) they are still beta IMO.

**Comment by envygeeks** [comment]
We are trying our first automated build right now.

**Comment by envygeeks** [comment]
Automated builds are enabled: https://registry.hub.docker.com/u/jekyll/jekyll/build_id/55906/code/bifbugh45hbtmau2qmbgbs4/
