### ISSUE TITLE
Detect bundle update and bundle clean and don't boot up the same way.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker#70]
Don't bundle install when updating and cleaning.  That's just silly.  Detect those commands and skip the install entirely and let them do their business without creating noisy cruft.

**Comment by parkr** [comment]
Where is this happening?

**Comment by envygeeks** [comment]
https://github.com/jekyll/docker/blob/master/copy/all/etc/startup1.d/03-gem-depends
