### ISSUE TITLE
Add jekyll-paginate by default.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker#76]
Is this gem really that popular @jekyll/core?

**Comment by jhabdas** [comment]
http://jekyllrb.com/docs/pagination/

> For Jekyll 3, include the jekyll-paginate plugin in your Gemfile and in your _config.yml under gems. For Jekyll 2, this is standard.

**Comment by envygeeks** [comment]
You can do that now as this image clearly states it supports Gemfile's.

**Comment by jhabdas** [comment]
@envygeeks. Thanks, I noticed that [in the `README.md`](https://github.com/jekyll/docker#gemfiles-and-gem-installation) but, after creating a `Gemfile` in my project using the `latest`, `stable` or `pages` images (and including `gem 'git'` I was not able to make it work.

**Comment by jhabdas** [comment]
FWIW looks like GitHub Pages doesn't support [jekyll-paginate](https://help.github.com/articles/using-jekyll-plugins-with-github-pages/), and I'd wager probably won't until they support Jekyll v3.

**Comment by jhabdas** [comment]
I lied https://pages.github.com/versions/

**Comment by bexelbie** [comment]
@jhabdas I also had problems getting this working.

This is what it took to work.

_config.yml:
gems: [jekyll-paginate, jekyll-feed]

Gemfile:
source 'https://rubygems.org'

group :jekyll_plugins do
  # These are from the _config.yml
  gem "jekyll-paginate"
  gem "jekyll-feed"
  # These are implicit from my use case
  gem "kramdown"
  gem "jekyll-watch"
end

**Comment by envygeeks** [comment]
@jhabdas @bexelbie both your issues are upstream bugs.  They'll be fixed there.

**Comment by jhabdas** [comment]
I pivoted

**Comment by envygeeks** [comment]
/cc @jekyll/core
/cc @parkr

If nobody objects this change will be implemented automatically tonight at Midnight.

**Comment by bexelbie** [comment]
I am not sure whose midnight is in question, but I was able to pull a new docker image.  The dockerfile seems to appropriately use the built-in gems now.

However, jekyll-paginate is still not included.

**Comment by envygeeks** [comment]
This should be on the list, I don't know why this ticket is dangling, but I'll double check tonight.

**Comment by jhabdas** [comment]
Thanks!
