### ISSUE TITLE
Broken readme link

### ISSUE THREAD

**Issue by geraldpereira** [jekyll/docker#80]
The link to the wiki that explains how to configure CI solutions to use this image is broken: [https://github.com/jekyll/docker/wiki/Deploying-with-Jekyll-Docker](https://github.com/jekyll/docker/wiki/Deploying-with-Jekyll-Docker)

Was it moved somewhere else ? I would like to use this image to build a Jekyll static website on Jenkins.

**Comment by envygeeks** [comment]
No somebody (probably me out of an accident) disabled the Wiki.  I've re-enabled the Wiki as it was a mistake and cleaned up that a page a bit.  All should be well now and feel free to edit it if you have any other tips not mentioned there.  I should probably update that page on how to use our image with Travis.
