### ISSUE TITLE
add timezone data in the image for `pages`

### ISSUE THREAD

**Issue by zym1010** [jekyll/docker#87]
It seems that the `timezone` feature in Jekyll (at least for the one in `pages` tag) needs package `tzdata` to work properly; otherwise, the timezone shown in the generated website is always GMT.

I tried to fix this in my own image <https://hub.docker.com/r/leelabcnbc/lab-website/~/dockerfile/>, and I hope this can be done in the base image (at least for `pages`), since timezone works properly on GitHub, but not on Docker image, which is somehow inconsistent the purpose of this Docker image.

**Comment by envygeeks** [comment]
Please file this issue at https://github.com/envygeeks/docker as this is an upstream issue.

**Comment by zym1010** [comment]
Done. Thanks!
