### ISSUE TITLE
GitHub now uses Jekyll 3.0 instead of 2.4

### ISSUE THREAD

**Issue by zym1010** [jekyll/docker#88]
Thus there should be an update to `pages` image.

**Comment by envygeeks** [comment]
Hulk: +block ++upstream:envygeeks/docker-template

**Comment by envygeeks** [comment]
Hi,

This is blocked by a need to update to the latest upstream, it will be resolved and a new template pushed as soon as possible, thanks for sending a reminder.

**Comment by envygeeks** [comment]
Hulk: -block --upstream:envygeeks/docker-template +schedule:release ++tomorrow

**Comment by envygeeks** [comment]
Hi; Hulk here. This issue has been unblocked pending a build tomorrow.
Thanks.

**Comment by zym1010** [comment]
Hi,
still no update?

**Comment by peterkokot** [comment]
This Docker container is really useful for Github pages also. I know my +1 vote wouldn't speed this up, but it would be very great for current version of GitHub pages to render accordingly.

**Comment by envygeeks** [comment]
Sorry for the late reply, this will be resolved tonight with the new push.
