### ISSUE TITLE
rsync missing

### ISSUE THREAD

**Issue by NioTeX** [jekyll/docker#90]
Hey guys, 

I am using the `jekyll/jekyll:builder` image, and it seems as it doesn't have rsync, when the documentation clearly says it does.

```bash
$ docker exec -it cf0f830ce8f8 rsync --help
exec: "rsync": executable file not found in $PATH
```
```bash
$ docker exec -it cf0f830ce8f8 bash
$ bash-4.3# rsync --help
bash: rsync: command not found
```

Any thoughts?
Thanks!

**Comment by envygeeks** [comment]
It seems like even though it's on the list it was never actually added to our dependency chain.  I'll be sure to add it as it's definitely useful for building and deployment!

**Comment by NioTeX** [comment]
https://github.com/jekyll/docker/pull/92 hope this helps

**Comment by NioTeX** [comment]
hey @envygeeks could you have a look at this?

Thanks :)

**Comment by envygeeks** [comment]
Hey, sorry it took so long for this to be fixed, we were stuck between a rock and a hard place since we needed to rebuild our upstream builder and implement it across all our clusters but that's finally done, this will be resolved in the next build tonight.

**Comment by thor** [comment]
@envygeeks stuff happens! :)
Nevertheless, big thanks for updating it and giving us notice. :+1:

**Comment by NioTeX** [comment]
@envygeeks thanks a lot, will try to use the official image with our build :)
