### ISSUE TITLE
Add support for Gemfile groups

### ISSUE THREAD

**Issue by kwisatz** [jekyll/docker#93]
Support for groups in Gemfiles would be great. For instance, I have a group defined for tests:

```ruby
group :test do
  gem 'cucumber', '~> 2.3'
  gem 'rspec-expectations'
  gem 'poltergeist', ">= 1.4.0"
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'rest-client'
  gem 'html-proofer'
end
```

I don't need these to be installed when I launch a container to develop the site or to build and deploy it, but only for tests at the end. If there's a way to do this already, I haven't found it. I'd imagine this could be handled by another environment variable perhaps?

The bundle command to install all but the gems in a group is 

```bash
bundle install --without test
```

**Comment by envygeeks** [comment]
Directly handling this is out of scope for our image, it's already handled multiple ways. Upstream `envygeeks/alpine` provides you access to `BUNDLE_ARGS` so you can do stuff through us without having to use your own commands and Bundler itself provides `BUNDLE_WITHOUT`.  We do not restrict or remove any environment variables you send.

**Comment by kwisatz** [comment]
Alright, thanks, that answers my question. I reckon I didn't read the docs of upstream images.

**Comment by envygeeks** [comment]
Gonna go ahead and document this behavior on our documentation because it's useful for all to know!
