### ISSUE TITLE
Jekyll / Guard and LiveReload

### ISSUE THREAD

**Issue by j12y** [jekyll/docker#97]
This is probably just a question / clarification so I'm looking for any advice.

I started a new site as an experiment `jekyll new .` and decided to give the docker image a try `docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 4000:4000 jekyll/jekyll` which worked as advertised and is great.

I added `-e POLLING=true` which successfully will regenerate the site when files are changed.  Also great.

Next I wanted to connect **guard** and **LiveReload** in my browser but ran into a few difficulties.  To get this working in the past I added my `Guardfile` and `Gemfile` with contents:
```
source 'https://rubygems.org'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
```

This doesn't go well, takes many minutes to start the container, installing 25 dependencies and ultimately results in a failure:
```
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
You are missing a library required for Markdown. Please run:
  $ [sudo] gem install kramdown
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2016-03-12-welcome-to-jekyll.markdown':
                    Missing dependency: kramdown
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Missing dependency: kramdown
```

Am I misunderstanding something about adding additional dependencies by providing my own Gemfile?

**Comment by envygeeks** [comment]
Hey, sorry.  I just noticed this ticket.  You need to do `-p live-reload-port:live-reload-port` to get LiveReload to work because the JS needs to be able to connect to Guard LiveReload inside of the instance.

**Comment by envygeeks** [comment]
This issue has been closed due to lack of a response.  If you continue to have problems please open another ticket.

Thanks!
